package keeper_test

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"forge.wavedidwhat.com/wave/ghoststake/internal/abis"
	"forge.wavedidwhat.com/wave/ghoststake/internal/keeper"
)

// The capability probes, against the bytecode forge actually produces.
//
// The synthetic tests beside this one prove the probes look in the right
// place. This proves they find the right answer in the real thing, which is
// the part that silently breaks: a compiler that inlined a selector
// differently, or a function removed from the contract, would leave the
// keeper confidently driving a market the wrong way. Skipped rather than
// failed when the artifacts are absent, because `go test ./...` must not
// require a `forge build`.
func deployedBytecode(t *testing.T, contract string) []byte {
	t.Helper()

	path := filepath.Join("..", "..", "..", "ghoststake-contracts", "out", contract+".sol", contract+".json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Skipf("no forge artifact for %s (run `forge build` in ghoststake-contracts): %v", contract, err)
	}

	var artifact struct {
		DeployedBytecode struct {
			Object string `json:"object"`
		} `json:"deployedBytecode"`
	}
	if err := json.Unmarshal(raw, &artifact); err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
	code, err := hex.DecodeString(strings.TrimPrefix(artifact.DeployedBytecode.Object, "0x"))
	if err != nil {
		t.Fatalf("decode %s bytecode: %v", contract, err)
	}
	if len(code) == 0 {
		t.Fatalf("%s has no deployed bytecode", contract)
	}
	return code
}

func TestTheProbesAgreeWithTheRealBytecode(t *testing.T) {
	event := deployedBytecode(t, "EventRoundOracle")
	price := deployedBytecode(t, "ChainlinkRoundOracle")

	if !keeper.IsEventOracle(event) {
		t.Fatal("EventRoundOracle is not recognised as one: the keeper would bind it to the price ABI, " +
			"fail to read feed(), and drop every market it drives")
	}
	if keeper.IsEventOracle(price) {
		t.Fatal("ChainlinkRoundOracle is recognised as a question: the keeper would stop reading its feed " +
			"and the market would never settle")
	}

	// The other half of the same decision, and the one already live on
	// Sepolia (GHO-79). Pinned here because both probes read the same
	// dispatch table and a change to one is the moment to re-check the other.
	if !keeper.SupportsStrikeAtOpen(deployedBytecode(t, "ParimutuelRound")) {
		t.Fatal("a freshly built market does not answer the four-argument openRound")
	}
}

func TestTheProbedFunctionsStillExist(t *testing.T) {
	// The artifact test above skips wherever `forge build` has not run, which
	// includes CI — so this is the half that always runs. It cannot see the
	// dispatch table, but it catches the failure that would actually happen:
	// a function renamed or removed in the contract, which turns a probe into
	// one that matches nothing and answers "no" forever.
	//
	// The ABIs are committed and regenerated by `make gen-abis`, so they move
	// with the contracts.
	for _, c := range []struct {
		contract string
		function string
	}{
		{abis.EventRoundOracle, "question"},
		{abis.ChainlinkRoundOracle, "feed"},
		{abis.ParimutuelRound, "openRound"},
	} {
		parsed, err := abis.Load(c.contract)
		if err != nil {
			t.Fatalf("load %s: %v", c.contract, err)
		}
		method, ok := parsed.Methods[c.function]
		if !ok {
			t.Fatalf("%s no longer has %s(), so the capability probe for it can never match",
				c.contract, c.function)
		}
		if c.function == "openRound" && len(method.Inputs) != 4 {
			t.Fatalf("openRound takes %d arguments, want 4 (GHO-79)", len(method.Inputs))
		}
	}
}
