/**
 * The gap between what the vault's ledger credits and what it can actually
 * pay out.
 *
 * `CollateralVault` keeps yield as a side ledger: `totalLedgerValue` is
 * principal plus banked yield plus yield pending since the last checkpoint,
 * and the contract says of it, in as many words, that "nothing funds this
 * yield ... `settledYield` is a claim against assets that do not exist".
 * `collateralValue` is that ledger capped at what the user's shares can
 * redeem, and the cap is load-bearing — it is what stops unfunded yield
 * becoming collateral somebody can borrow against.
 *
 * That is all correct and it should stay. The problem GHO-55 is about is that
 * the app rendered the ledger's yield as `+11.5596 earned` beside the balance,
 * which is the universal grammar for money you have, when on the Sepolia
 * deployment `maxWithdraw` equalled the principal *exactly* and none of it was
 * ever withdrawable.
 *
 * Derived from the two figures rather than asserted in copy. If the vault is
 * ever funded — a donation lifts the share price, and the cap stops binding —
 * this reports it backed without anybody editing a string. A UI that hardcoded
 * "yield is never redeemable" would be telling a new lie the moment that
 * happened.
 */
export type StakeStanding = {
  /** What the shares can actually redeem: `collateralValue`. */
  redeemable: bigint;
  /** What the ledger credits: `totalLedgerValue`. */
  ledger: bigint;
  /** The part of the ledger no assets stand behind. Never negative. */
  unbacked: bigint;
  /** Whether the ledger is covered, to the precision anything is displayed at. */
  backed: boolean;
};

/**
 * Dust tolerance, in display units.
 *
 * `collateralValue` is a `min` of two independently-rounded quantities, so it
 * can sit a few wei under the ledger on a position that is fully funded.
 * Without a floor, one wei of rounding would put a "not redeemable" warning on
 * a healthy position — a scary sentence generated by arithmetic noise, which
 * is its own kind of dishonesty.
 *
 * The floor is one unit at the four decimal places amounts are rendered to:
 * below that the difference cannot be seen on screen anyway.
 */
export function dustFloor(decimals: number, fractionDigits = 4): bigint {
  const scale = decimals - fractionDigits;
  return scale > 0 ? 10n ** BigInt(scale) : 1n;
}

export function stakeStanding(
  ledger: bigint | undefined,
  redeemable: bigint | undefined,
  decimals: number | undefined,
): StakeStanding | undefined {
  if (ledger === undefined || redeemable === undefined || decimals === undefined) {
    return undefined;
  }
  const shortfall = ledger > redeemable ? ledger - redeemable : 0n;
  return {
    redeemable,
    ledger,
    unbacked: shortfall,
    backed: shortfall < dustFloor(decimals),
  };
}
