import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Paths are resolved from this file, not the cwd, so the script works the
// same from the package root, the repo root, or a CI step.
const here = path.dirname(fileURLToPath(import.meta.url));
const contracts = path.resolve(here, "../../ghoststake-contracts");
const target = path.resolve(here, "../src/lib/abis.ts");

// Only the functions the UI actually calls — reads and writes both. A full
// ABI carries entries nothing touches, which bloats the bundle and obscures
// what is wired up. If a name here is missing from the artifact the script
// throws, so a renamed function fails the build rather than silently
// producing a UI that calls nothing.
const WANTED = {
  CollateralVault: [
    "asset", "decimals", "balanceOf", "convertToAssets", "convertToShares",
    "collateralValue", "totalLedgerValue", "accruedYield",
    "lienOf", "healthFactor", "maxBorrowable", "isLiquidatable",
    "liquidationThreshold", "maxLTV",
    // writes
    "deposit", "withdraw", "redeem", "borrow", "repay",
    "approveBorrowDelegate", "borrowAllowance",
  ],
  ParimutuelRound: [
    "rounds", "roundCount", "phaseOf", "claimableOf", "stakeOf", "claimed",
    "entryCutoff", "minSidePool", "rake", "stakeAsset",
    // writes
    "takePosition", "claim",
  ],
  BorrowToPositionRouter: [
    "vault", "market", "asset",
    // writes
    "openPosition",
  ],
  BorrowLiquidityPool: [
    "balanceOfDebt", "balanceOfSupply", "utilization",
    "borrowRatePerSecond", "availableLiquidity", "totalBorrowed", "totalSupplied",
  ],
};

const out = [];
out.push("// GENERATED by scripts/generate-abis.mjs — do not edit by hand.");
out.push("// Regenerate with: pnpm gen:abis (after `forge build` in ghoststake-contracts).");
out.push("//");
out.push("// Only the read functions the UI displays are included; see the script.");
out.push("");

for (const [name, wanted] of Object.entries(WANTED)) {
  const artifactPath = path.join(contracts, "out", `${name}.sol`, `${name}.json`);
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
  const picked = artifact.abi.filter(
    (e) => e.type === "function" && wanted.includes(e.name),
  );
  const missing = wanted.filter((w) => !picked.some((p) => p.name === w));
  if (missing.length) throw new Error(`${name}: not found in ABI: ${missing.join(", ")}`);
  out.push(`export const ${name.charAt(0).toLowerCase()}${name.slice(1)}Abi = ${JSON.stringify(picked, null, 2)} as const;`);
  out.push("");
  console.error(`${name}: ${picked.length} functions`);
}

fs.writeFileSync(target, out.join("\n"));
