import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Paths are resolved from this file, not the cwd, so the script works the
// same from the package root, the repo root, or a CI step.
const here = path.dirname(fileURLToPath(import.meta.url));
const contracts = path.resolve(here, "../../ghoststake-contracts");
const target = path.resolve(here, "../src/lib/abis.ts");

// Only the functions the UI actually calls — reads and writes both. A full
// ABI carries entries nothing touches, which bloats the bundle and obscures
// what is wired up. If a name here is missing from the artifact the script
// throws, so a renamed function fails the build rather than silently
// producing a UI that calls nothing.
const WANTED = {
  CollateralVault: [
    "asset", "decimals", "balanceOf", "convertToAssets", "convertToShares",
    "collateralValue", "totalLedgerValue", "accruedYield",
    "lienOf", "healthFactor", "maxBorrowable", "isLiquidatable",
    "liquidationThreshold", "maxLTV", "yieldRatePerSecond", "liquidationBonus", "closeFactor",
    // writes
    "deposit", "withdraw", "redeem", "borrow", "repay",
    "approveBorrowDelegate", "borrowAllowance",
    // The liquidator's surface (GHO-42). `maxLiquidatableDebt` is read
    // straight from the contract rather than trusted from the API: the API's
    // figure is a quote computed at its own block, and this is the number the
    // transaction will actually be held to.
    "maxLiquidatableDebt", "liquidate", "writeOffBadDebt",
  ],
  ParimutuelRound: [
    "rounds", "roundCount", "phaseOf", "claimableOf", "stakeOf", "claimed",
    "entryCutoff", "minSidePool", "rake", "stakeAsset", "oracle",
    "lockWindow", "resolveDeadline", "entryIsOpen", "owner",
    // writes
    "takePosition", "claim",
    // the operator console (GHO-28). `lockRound`, `resolveRound` and
    // `voidUnlockedRound` are permissionless by design; `openRound` and
    // `voidUnsettledRound` are owner-only, and the page says which is which
    // rather than hiding the ones a visitor may call.
    "openRound", "lockRound", "resolveRound", "voidUnsettledRound", "voidUnlockedRound",
    // The fees panel (GHO-40). The rake accrued in `protocolFees` and the only
    // way to move it was `cast send`. `treasury` and `setTreasury` are read
    // and written here so the destination is stated before anything is signed
    // rather than typed into a terminal.
    "protocolFees", "withdrawFees", "treasury", "setTreasury",
  ],
  // The testnet stand-in asset. `mint` is open by design on a disposable
  // chain, which is what lets the UI offer test tokens without a CLI.
  MockUSDC: ["mint", "decimals", "symbol", "balanceOf"],
  BorrowToPositionRouter: [
    "vault", "market", "asset",
    // writes
    "openPosition",
  ],
  // Two hops from a market to the feed behind it — `market.oracle()`, then
  // `oracle.feed()`, then `feed.description()`. The UI walks that chain so it
  // can say where a market's settlement price actually comes from instead of
  // trusting which env var the address arrived in (GHO-29).
  ChainlinkRoundOracle: ["feed", "maxStaleness", "readAt", "readLatest"],
  AggregatorV3Interface: ["description", "decimals", "getRoundData", "latestRoundData"],
  // The operator-driven feed behind a demo market (GHO-29). Only reachable
  // where such a market is deployed; the console hides it otherwise.
  DemoPriceFeed: ["push", "pushAt", "latestRoundId", "owner", "description", "decimals"],
  // The list of markets the app offers (GHO-34). `all` in one call, because
  // the alternative is a request per market and a list that trickles in.
  MarketRegistry: ["all", "count", "at", "find"],
  BorrowLiquidityPool: [
    // `asset` is read rather than assumed to be the vault's: the pool takes
    // its own asset in the constructor and nothing forces the two to match.
    "asset",
    "balanceOfDebt", "balanceOfSupply", "utilization",
    "borrowRatePerSecond", "supplyRatePerSecond",
    "availableLiquidity", "totalBorrowed", "totalSupplied",
    // The curve's target, so the lender surface can say *why* a rate is high
    // instead of showing a number with no scale behind it (GHO-39).
    "kink",
    // writes — the supply side, which had no way into the app at all until
    // GHO-39. Every borrow drew from a pool only `Seed.s.sol` could fill.
    "supply", "withdraw",
    // The fees panel (GHO-40).
    "totalReserves", "withdrawReserves", "treasury", "setTreasury", "owner",
  ],
};

const out = [];
out.push("// GENERATED by scripts/generate-abis.mjs — do not edit by hand.");
out.push("// Regenerate with: pnpm gen:abis (after `forge build` in ghoststake-contracts).");
out.push("//");
out.push("// Only the read functions the UI displays are included; see the script.");
out.push("");

for (const [name, wanted] of Object.entries(WANTED)) {
  const artifactPath = path.join(contracts, "out", `${name}.sol`, `${name}.json`);
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
  const picked = artifact.abi.filter(
    (e) => e.type === "function" && wanted.includes(e.name),
  );
  const missing = wanted.filter((w) => !picked.some((p) => p.name === w));
  if (missing.length) throw new Error(`${name}: not found in ABI: ${missing.join(", ")}`);
  out.push(`export const ${name.charAt(0).toLowerCase()}${name.slice(1)}Abi = ${JSON.stringify(picked, null, 2)} as const;`);
  out.push("");
  console.error(`${name}: ${picked.length} functions`);
}

fs.writeFileSync(target, out.join("\n"));
