#!/usr/bin/env bash
#
# Deploys and seeds GhostStake to a real network, using YOUR key.
#
#   NETWORK=robinhood-testnet ./scripts/deploy-network.sh
#
# The deployer is whoever signs, and the seeded position lands on that same
# address — so connecting the wallet that ran this shows a funded dashboard
# with nothing to import and nothing to transfer.
#
# Put PRIVATE_KEY in ghoststake-contracts/.env (gitignored). It never leaves
# your machine.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NETWORK="${NETWORK:-robinhood-testnet}"

case "$NETWORK" in
  robinhood-testnet)
    RPC_URL="${RPC_URL:-https://rpc.testnet.chain.robinhood.com}"
    CHAIN_ID=46630
    EXPLORER="https://explorer.testnet.chain.robinhood.com"
    ;;
  ethereum-sepolia)
    RPC_URL="${RPC_URL:-https://ethereum-sepolia-rpc.publicnode.com}"
    CHAIN_ID=11155111
    EXPLORER="https://sepolia.etherscan.io"
    # Verified on-chain by calling description(), not copied from a docs page.
    # An L1, so there is no sequencer uptime feed and none is needed — the
    # zero address is correct here rather than a compromise.
    FEED_ADDRESS="${FEED_ADDRESS:-0x694AA1769357215DE4FAC081bf1f309aDC325306}"  # ETH / USD, 8 dp
    ;;
  arbitrum-sepolia)
    RPC_URL="${RPC_URL:-https://sepolia-rollup.arbitrum.io/rpc}"
    CHAIN_ID=421614
    EXPLORER="https://sepolia.arbiscan.io"
    ;;
  *)
    echo "unknown NETWORK '$NETWORK' (ethereum-sepolia | robinhood-testnet | arbitrum-sepolia)" >&2
    exit 1
    ;;
esac

export ARBISCAN_API_KEY="${ARBISCAN_API_KEY:-}"
export FEED_ADDRESS="${FEED_ADDRESS:-}"
export SEQUENCER_FEED_ADDRESS="${SEQUENCER_FEED_ADDRESS:-}"
log() { printf '\033[1;35m▸\033[0m %s\n' "$*"; }

cd "$ROOT/ghoststake-contracts"
set -a && . ./.env && set +a

if [ -z "${PRIVATE_KEY:-}" ]; then
  echo "PRIVATE_KEY is not set in ghoststake-contracts/.env" >&2
  exit 1
fi

DEPLOYER="$(cast wallet address --private-key "$PRIVATE_KEY")"

# Checked before spending anything: a deploy that runs out of gas halfway
# leaves contracts half-wired, and the vault's lien source is immutable so
# the fix is a redeploy rather than a setter.
BALANCE="$(cast balance "$DEPLOYER" --rpc-url "$RPC_URL")"
log "network   $NETWORK (chain $CHAIN_ID)"
log "deployer  $DEPLOYER"
log "balance   $(cast to-unit "$BALANCE" ether) ETH"
if [ "$BALANCE" = "0" ]; then
  echo "deployer has no gas on this network. Fund $DEPLOYER and re-run." >&2
  exit 1
fi

ACTUAL_CHAIN="$(cast chain-id --rpc-url "$RPC_URL")"
if [ "$ACTUAL_CHAIN" != "$CHAIN_ID" ]; then
  echo "RPC reports chain $ACTUAL_CHAIN, expected $CHAIN_ID" >&2
  exit 1
fi

log "deploying"
if ! DEPLOY_OUT="$(forge script script/Deploy.s.sol:Deploy --rpc-url "$RPC_URL" \
    --broadcast --slow --gas-estimate-multiplier 200 2>&1)"; then
  echo "$DEPLOY_OUT" >&2
  exit 1
fi
addr_of() { echo "$DEPLOY_OUT" | grep -E "^\s+$1\s+0x" | awk '{print $NF}'; }

ASSET=$(addr_of "Asset"); POOL=$(addr_of "BorrowLiquidityPool")
VAULT=$(addr_of "CollateralVault"); MARKET=$(addr_of "ParimutuelRound")
ROUTER=$(addr_of "BorrowToPositionRtr")
START_BLOCK=$(echo "$DEPLOY_OUT" | grep -oE "INDEXER_START_BLOCK=[0-9]+" | cut -d= -f2)

if [ -z "$VAULT" ] || [ -z "$POOL" ] || [ -z "$MARKET" ]; then
  echo "$DEPLOY_OUT" >&2
  echo "could not parse deployed addresses — see output above" >&2
  exit 1
fi

log "seeding"
# Gas is estimated with headroom for the same reason as the deploy, and the
# output is captured rather than piped: a pipeline under `set -o pipefail`
# takes the whole script down before the env files below are written, which
# is how a successful deploy ended up unusable twice.
if ! SEED_OUT="$(ASSET_ADDRESS="$ASSET" POOL_ADDRESS="$POOL" VAULT_ADDRESS="$VAULT" MARKET_ADDRESS="$MARKET" \
    forge script script/Seed.s.sol:Seed --rpc-url "$RPC_URL" \
    --broadcast --slow --gas-estimate-multiplier 200 2>&1)"; then
  echo "$SEED_OUT" >&2
  echo "seeding failed — the contracts are deployed, so re-run the seed rather than the deploy" >&2
  exit 1
fi
echo "$SEED_OUT" | sed -n '/=== seeded ===/,/healthFactor/p' || true

cat >"$ROOT/ghoststake-frontend/.env.local" <<ENV
# Generated by scripts/deploy-network.sh ($NETWORK)
NEXT_PUBLIC_API_URL=http://localhost:8080
NEXT_PUBLIC_CHAIN_ID=$CHAIN_ID
NEXT_PUBLIC_RPC_URL=$RPC_URL
NEXT_PUBLIC_VAULT_ADDRESS=$VAULT
NEXT_PUBLIC_POOL_ADDRESS=$POOL
NEXT_PUBLIC_MARKET_ADDRESS=$MARKET
NEXT_PUBLIC_ROUTER_ADDRESS=$ROUTER
ENV

cat >"$ROOT/ghoststake-backend/.env.local" <<ENV
# Generated by scripts/deploy-network.sh ($NETWORK)
CHAIN_ID=$CHAIN_ID
ARBITRUM_RPC_URL=$RPC_URL
INDEXER_ENABLED=true
INDEXER_START_BLOCK=${START_BLOCK:-1}
INDEXER_CONFIRMATIONS=5
VAULT_ADDRESS=$VAULT
POOL_ADDRESS=$POOL
ENV

cat <<SUMMARY

  $(printf '\033[1;32m✓ deployed to %s\033[0m' "$NETWORK")

  Asset                 $ASSET
  BorrowLiquidityPool   $POOL
  CollateralVault       $VAULT
  ParimutuelRound       $MARKET
  BorrowToPositionRtr   $ROUTER

  $EXPLORER/address/$VAULT

  Connect $DEPLOYER and the position is already there.
  Env files written for both packages.

SUMMARY
