// Generated by flute sync. Edit recipes and components, not this registry.
import recipe0 from "./scenes/live-round.scene.json";
import recipe1 from "./scenes/markets-survey.scene.json";
import recipe2 from "./scenes/pitch-hero.scene.json";
import recipe3 from "./scenes/portfolio-health.scene.json";
export const sceneModules = {
  "src/flute/scenes/live-round.scene.json": async () => ({default:recipe0}),
  "src/flute/scenes/live-round.tsx": () => import("./scenes/live-round"),
  "src/flute/scenes/markets-survey.scene.json": async () => ({default:recipe1}),
  "src/flute/scenes/markets-survey.tsx": () => import("./scenes/markets-survey"),
  "src/flute/scenes/pitch-hero.scene.json": async () => ({default:recipe2}),
  "src/flute/scenes/pitch-hero.tsx": () => import("./scenes/pitch-hero"),
  "src/flute/scenes/portfolio-health.scene.json": async () => ({default:recipe3}),
  "src/flute/scenes/portfolio-health.tsx": () => import("./scenes/portfolio-health"),
};
